name: CI for NestJS

on:
  push:
  pull_request:

jobs:
  build-n-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Test the application
        run: npm run test:e2e
